# Generated by Django 4.0.5 on 2022-06-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_locationdatetime_slots'),
        ('users', '0002_account_location_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location_date_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.locationdatetime'),
        ),
    ]
