# Generated by Django 4.0.5 on 2022-06-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_alter_locationdatetime_unique_together_and_more'),
        ('users', '0003_alter_account_location_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='location_date_time',
        ),
        migrations.AddField(
            model_name='account',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.appointment'),
        ),
    ]
