# Generated by Django 4.0.5 on 2022-06-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_account_location_date_time_and_more'),
        ('booking', '0004_appointment_alter_locationdatetime_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationDateTime',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.location'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('location', 'date', 'time')},
        ),
    ]
